### ISSUE TITLE
креды для подключения

### ISSUE THREAD

**Issue by b4d63rus** [unixzen/yc-billing-exporter#2]
Привет! Правильно я понял, что для подключения нужен IAM Token service account с доступом к billing-account и billing-account id?

**Comment by unixzen** [comment]
> Привет! Правильно я понял, что для подключения нужен IAM Token service account с доступом к billing-account и billing-account id?

Привет! Для подключения нужен oAuth токен, потом экспортер меняет его на IAM токен (https://yandex.cloud/ru/docs/iam/operations/iam-token/create#api_1) ранее в документации у яндекса было написано, что нельзя использовать сервисные аккаунты для доступа к биллингу, я написал в поддержку, мне подтвердили, что это так поэтому экспортер сделан так. Через некоторое время в поддержке мне ответили, что дали сперва мне неверную информацию и на самом деле можно использовать сервисные аккаунты для доступа к биллингу, но я потом не стал уже переписывать, а оставил так. 

Запускается так (перед запуском нужно скомпилировать):

`TOKEN=<oAuth-token> YCBILLINGID=<billing_id> main` 

Метрики будут по URL
http://127.0.0.1:2112/metrics

На этой или следующей неделе если интересно могу написать README и подготовить Dockerfile для сборки docker образа.

Если нужно переписать для использования сервисного аккаунта создай пожалуйста новый issue.

**Comment by b4d63rus** [comment]
Спасибо! Да, с README было бы удобнее, issue сделаю.

**Comment by unixzen** [comment]
> Спасибо! Да, с README было бы удобнее, issue сделаю.

Я тогда сперва перепишу экспортер (https://github.com/unixzen/yc-billing-exporter/issues/3), чтобы можно было сервисный аккаунт использовать, а потом тогда README, чтобы 2 раза не переписывать.
